### ISSUE TITLE
unicode decode error

### ISSUE THREAD

**Issue by ralphbean** [sochotnicky/fedwatch#9]
I hit this today:

```python
fedwatch - ERROR - runtime exception: 'ascii' codec can't encode character u'\u0161' in position 2092: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/bin/fedwatch", line 101, in <module>
    fw.watch()
  File "/usr/lib/python2.7/site-packages/fedwatch.py", line 144, in watch
    self.__run_scripts(self.script_dir, pargs)
  File "/usr/lib/python2.7/site-packages/fedwatch.py", line 89, in __run_scripts
    procarg.extend([str(parg) for parg in pargs])
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0161' in position 2092: ordinal not in range(128)
```

**Comment by sochotnicky** [comment]
You wouldn't happen to have a time when this happened? Or better yet the message. 

I will likely just need proper encode instead of dummy str() I did...

**Comment by sochotnicky** [comment]
Yeah, I vaguely remember when this was done here:
https://github.com/sochotnicky/fedwatch/commit/29a9a98d05ef45898e1e7be6bc87277ba3fa6a69

I guess I'll have to check and if it's a type of string - encode utf-8
